name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Racket environment
        uses: Bogdanp/setup-racket@v1.10
        with:
          version: 'stable'
      - name: Start ClamAV daemon (clamd)
        uses: toblux/start-clamd-github-action@main
      - name: Install packages and run tests
        run: make ci
      - name: Shutdown clamd
        run: echo SHUTDOWN | nc localhost 3310
