name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Racket environment
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          version: 'stable'
      - name: Install ClamAV daemon
        run: sudo apt-get install clamav-daemon
      - name: Update ClamAV virus databases
        run: |
          sudo systemctl stop clamav-freshclam
          sudo freshclam
      - name: Start clamd
        run: clamd --config-file=clamav-client-test/clamd.conf
      - name: Install packages and run tests
        run: make ci
      - name: Shutdown clamd
        run: echo SHUTDOWN | nc localhost 3310
