name: Run tests
on: [push, pull_request]

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Racket environment
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: 'stable'
      - name: Start ClamAV daemon (clamd)
        uses: toblux/start-clamd-github-action@main
      - name: Install packages and run tests
        run: make ci
      - name: Shutdown clamd
        run: echo SHUTDOWN | nc localhost 3310
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Racket environment
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: 'stable'
      - name: Start ClamAV daemon (clamd)
        uses: toblux/start-clamd-github-action@main
      - name: Install packages and run tests
        run: make ci
      - name: Shutdown clamd
        run: echo SHUTDOWN | nc localhost 3310
